# Generated by Django 5.2.7 on 2025-10-31 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name or title of the event.', max_length=511, verbose_name='Event Name')),
                ('short_description', models.CharField(help_text='A brief summary of the event, usually one sentence.', max_length=511, verbose_name='Short Description')),
                ('long_description', models.TextField(help_text='Detailed information about the event or additional details.', verbose_name='Long Description')),
                ('event_time', models.DateTimeField(help_text='The time and day when the event is scheduled to occur.', verbose_name='Event Date and Time')),
                ('location', models.CharField(help_text='The area or location where the event will take place.', max_length=511, verbose_name='Event Location')),
                ('image', models.ImageField(help_text='A poster or image for the event.', upload_to='event_posters/', verbose_name='Event Image')),
                ('contact_email', models.EmailField(help_text='The contact email for the event, used for questions or responses.', max_length=254, verbose_name='Event Contact Email')),
                ('notes_for_slo', models.TextField(blank=True, help_text='Internal notes for the Student Life Office regarding this event.', null=True, verbose_name='Notes for SLO')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', help_text='The current approval status of the event: pending, approved, or denied.', max_length=20, verbose_name='Event Status')),
                ('reason_denied', models.TextField(blank=True, help_text='If the event is denied, the reason for denial is provided.', null=True, verbose_name='Reason Denied')),
                ('time_submitted', models.DateTimeField(auto_now_add=True, help_text='The time and day the event was first submitted.', verbose_name='Time Submitted')),
                ('last_submitted', models.DateTimeField(auto_now=True, help_text='The time and day the event was last submitted or resbmitted for approval.', verbose_name='Last Submitted')),
                ('created_by', models.ForeignKey(help_text='The student or user who submitted or created the event.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', help_text='Whether the user will attend the event (yes, no).', max_length=5, verbose_name='RSVP Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the RSVP was created.', verbose_name='RSVP Created At')),
                ('event', models.ForeignKey(help_text='The event the user is RSVPing to.', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='events.event', verbose_name='Event')),
                ('user', models.ForeignKey(help_text='The user who is RSVPing for the event.', on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
