# Generated by Django 5.2.7 on 2025-11-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_time',
            field=models.DateTimeField(blank=True, help_text='If it is appropriate, the time and day when the event is scheduled to end.', null=True, verbose_name='Event Ending Date and Time'),
        ),
    ]
